#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx restart
