#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
