#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\* -y
sudo echo "frontend web
bind *:80
mode http
default_backend web
option tcplog

backend web
balance roundrobin
mode http
server server1 44.200.190.25:80 check
server server2 44.192.252.60:80 check" >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
