#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays bad luck for the 4th loop iteration displays good luck for the 8th loop iteration and displays Best School for the other iterations
n=0
while [ $n -lt 10 ];
do
	if [ "$n" = 3 ]
	then
		echo "bad luck"
	elif [ "$n" = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
