#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iterationI
n=0
while [ $n -lt 20 ];
do echo "$n"
	case "$n" in
        3)  echo "bad luck from China";;
        8)  echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
	esac
        ((n++))
done

