#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
n=0
while [ $n -lt 12 ];
do
	echo "Hour: $n"
	i=1
	while [ $i -lt 60 ];
	do
		echo "$i"
		((i++))
	done
	((n++))
done
