#!/usr/bin/env bash
# Get apache to run on a docker container and return Hello Holberton when querying the root of it
sudo apt-get update
sudo apt-get install apache2 -y
sudo apt-get install systemd -y
apachectl start
